services:
  postgres:
    image: postgres:16
    container_name: recipebook_db
    environment:
      POSTGRES_DB: recipebook
      POSTGRES_USER: recipebook_user
      POSTGRES_PASSWORD: recipebook_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: